In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

In [6]:
#Data_Sets
#Read Data_sets
file_path1 = 'Data/COVID-19_ziekenhuisopnames_1of2.csv'
covid_temp1 = pd.read_csv(file_path1, delimiter = ';',  parse_dates=['Date_of_statistics'], index_col = 'Date_of_statistics')

file_path2 = 'Data/COVID-19_ziekenhuisopnames_2of2.csv'
covid_temp2 = pd.read_csv(file_path2, delimiter = ';',  parse_dates=['Date_of_statistics'], index_col = 'Date_of_statistics')

    #Merge both Data_sets
covid = pd.merge(covid_temp1, covid_temp2, how = 'outer')
covid
# covid.Hospital_admission.resample('M' ,kind='period').sum()
#for i in covid['Date_of_statistics']:
 #   print(i.month)

,Version,Date_of_report,Municipality_code,Municipality_name,Security_region_code,Security_region_name,Hospital_admission_notification,Hospital_admission
0,6,4-10-2022 00:30,GM0014,Groningen,VR01,Groningen,0,1
1,6,4-10-2022 00:30,GM0014,Groningen,VR01,Groningen,0,1
2,6,4-10-2022 00:30,GM0014,Groningen,VR01,Groningen,0,1
3,6,4-10-2022 00:30,GM0014,Groningen,VR01,Groningen,0,1
4,6,4-10-2022 00:30,GM0014,Groningen,VR01,Groningen,0,1
...,...,...,...,...,...,...,...,...
327745,6,2-9-2022 00:30,GM0599,Rotterdam,VR17,Rotterdam-Rijnmond,10,5
327746,6,2-9-2022 00:30,GM0938,Meerssen,VR24,Limburg-Zuid,2,1
327747,6,2-9-2022 00:30,GM0599,Rotterdam,VR17,Rotterdam-Rijnmond,14,2
327748,6,2-9-2022 00:30,GM0599,Rotterdam,VR17,Rotterdam-Rijnmond,7,5
327749,6,2-9-2022 00:30,GM0114,Emmen,VR03,Drenthe,5,1

In [7]:
covid_province = covid.groupby(['Date_of_statistics', 'Security_region_name']).sum()
covid_province.reset_index(inplace=True)
#covid_province['Datetime'] = pd.to_datetime(covid_province['Date_of_publication'])
fig = px.scatter(covid_province, x = 'Date_of_statistics',  y = 'Hospital_admission', color = 'Security_region_name')
fig.update_yaxes(range = [0, 100])

KeyError: 'Date_of_statistics'